# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Language options
language: node_js
node_js:
  - '0.10'

# SAUCE_TOKENS for zuul
env:
  global:
  - secure: Z1bW8cIMqS4xqesgrSbKx8cVgYFAdPLHHfTGdwjyZ1bdaKRXpsXcM5JPYjQznnuO1cH3kAKoYWlXaFbNUu0AcwvTX5ex004UYL0lLflMB8N9Qs3Hw2HuO3a1eCNX9fNeukyPGMOUmt8lQjEzpETFQVHboS3ptPTe/jB1v08i+/WISkgQ404sLLJr7YiUy19wcaikWjIzjPhCrZWeW+B6RQR/eZSu1k7Hxr+wN8wUHcV3++FIaRcYG2pwmkrhSznBWvR969PhR0Y4OsojhZzZEWybB7mK9VbewJ0d2g6e/DNdS6a6T3q77kgVc77ysIA4kd6NwGmm1WUvCwdR0MSLjDmKtlXOvu5GIR5/IXvYueAAas9gdZVm1QcsxLvFngzP+x15MsuqDpAOnmrhFvlaPgTWMcc5eJmms5o164IBpBl8D2beJbxk0r8yWum1yYRmcGyCSSfL57QVYs3CS18ZUKNUexLtxdGIu5Yqf6UfHAaC+xThq/31R6oUqQZEjzEhTdzIOl78r5eDvbFzG/+YiL7iKgkvZPnoejh0Pr5KooEOvfgMjbrulZTULWhOPbOvSan9T9/gjopTxgtF9vUwfE/91mItwwwy6xo4qVBwLcxmUcigu6Ir+QYZKsOBBg04n903pzaUVBSjKjIFNAGU27g3MXN9szO75xDd15QI2MA=
  - secure: iZFiyv3MMg0eTx/DVQkTHfc9x6rsYkhWvF5SKXyKwDOijKH8YXcz4yJxq9x/BH/OyKZpkBNRTFtcZdyov4FEt50c22pqVMswl/lvfrl0foGL2OVCjL7SskfPpeUwAww8y/PL79LJ8+D6reZ7Wz7PMcxIIuUHZA+wWdZIrtCeBUzMgrspVPOdFaFKb09R0n06/Zvg3zE3iXI3b4xGf9SG+UGQvwxdc/FrQEUc5LW/VCV4gvIAnbQRGfkvG5LK2NBlaebcziyPFXVvAEsJWeD2DlfBIPr3mBX3cl9NbWgKZ4N1TT0yNfC9iNhJz/yJP1Olw6DjgJ9FrnwasrwBXh9IDV2ISOb5LJycoa5RAPwtm9U9z/4hojHFlb0H6lyyR2v9nHioEHUZ13I0ouKC5K7GWT7f10giaAwVWpFuATMfU+djiVfdvGvezYhpxemkDuKSpbFpghZ+K5xEX9c0xJ5Z/NrA2wm7BK2PcwmpqkZETdjJ4OOkLh1igZwZNafSrHEqpUVQMvBeXz64InTG4JBm6asTCZCxOGsvTzD+IYmefr25YfGiC0UxFJlRYxL78ww1Y70d86S0+zCqqOoQ2ba3qJn6JiBiiWOok1a91lwsH9AeM2TFqvLHDyPTmlwk09USzRCBhAtWW3Y7+l1JGO8mOK/Wa4o25tnANCIc/bWUgaY=

# Npm publish options
deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: T0g37IEpOhgtAHQsAcooBiKFH2aw4kPAhxwi+IeCQ/BEjaItpqI+tmSJVrUlCbf8tkubQZByKWI7UmBoRkPoAdRIJ4Azyan71oSYF7gOn2BfLwVpl1k1Ty0aL4KfEMH3AW8AurfRskhH43z5pByEtPyEzmlTyM3jHPuyBQ1KG2noveTbBx/3PlxOvGyvqlTpW2u52kInAWAf9n4ugfu0QCor9YjYJobQHK2U0hJe7rQKzqMhcAkuFYIrR12l+yY7QpaixTZJ1P8Zj4qQh4MgjIMIhh1RGjNQObxJuR8ore4m0NSMnsPqxS/OKfwDfuNODrr+lgwrBJ1E8C726/sOMMZVwi4/8LdkJQ7FUp3Hb8YfSdkR8FQxhwZvB8xs/cWwCsFFxJ6ZGjpiDPslVEgOktBdR584E67JQLdYeFENoUeUPtddb5Dp400FU2NIuVoRXTt9tpzq/1KAOOmCxah2ngknApUuGufcMhHHpIuQ6dd2BjxDVgiAjorG96IzOBwDVt2geOKGWGDb+xrFlOsl8eVG2VWgQvdky3GR3Ayv9HHF5motrsMKL01uNCXJhE2FboPjhsytq8i+nG8t2g8NquJ4JqLZMP4OBkixKZ+kmG+q3mnHnpKFlV79o4gxfkP21T7LPHx00gSBnU5/SHqDZpidb8DP6DuZzXMXbnqeK08=